version: "3"
services:
    public_server:
        image: wesen1/assaultcube-wesen-gema-mod-server:latest
        restart: unless-stopped
        environment:
          DATABASE_NAME: ${DATABASE_NAME}
          DATABASE_USER: ${DATABASE_USER}
          DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        ports:
            - "28763:28763/udp"
            - "28764:28764/udp"
        volumes:
            - ./shared-data/config:/ac-server/config/shared:rw
            - ./public-server/config:/ac-server/config:rw
            - ./shared-data/packages:/ac-server/packages:rw
            - ./shared-data/demos/public:/ac-server/demos
            - ./public-server/config.lua:/ac-server/lua/config/config.lua:rw
            - ./shared-data/geoip-data:/usr/share/GeoIP
        networks:
          - database
        depends_on:
          - database
          - geoip-updater

    private_server:
        image: wesen1/assaultcube-wesen-gema-mod-server:latest
        restart: unless-stopped
        environment:
          DATABASE_NAME: ${DATABASE_NAME}
          DATABASE_USER: ${DATABASE_USER}
          DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        ports:
            - "11111:28763/udp"
            - "11112:28764/udp"
            - "1111:28763/udp"
            - "1112:28764/udp"
        volumes:
            - ./shared-data/config:/ac-server/config/shared:rw
            - ./private-server/config:/ac-server/config:rw
            - ./shared-data/packages:/ac-server/packages:rw
            - ./shared-data/demos/private:/ac-server/demos
            - ./private-server/config.lua:/ac-server/lua/config/config.lua:rw
            - ./shared-data/geoip-data:/usr/share/GeoIP
        networks:
          - database
        depends_on:
          - database
          - geoip-updater

    database:
      image: mysql/mysql-server:5.7
      container_name: database
      environment:
        MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
        MYSQL_DATABASE: ${DATABASE_NAME}
        MYSQL_USER: ${DATABASE_USER}
        MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      networks:
        - database
      volumes:
        - ./shared-data/mysql-data:/var/lib/mysql:rw

    geoip-updater:
      image: maxmindinc/geoipupdate
      environment:
        GEOIPUPDATE_ACCOUNT_ID: ${GEOIP_ACCOUNT_ID}
        GEOIPUPDATE_LICENSE_KEY: ${GEOIP_LICENSE_KEY}
        GEOIPUPDATE_EDITION_IDS: GeoLite2-Country
        GEOIPUPDATE_FREQUENCY: 24
      volumes:
        - ./shared-data/geoip-data:/usr/share/GeoIP

networks:
  database:
